asset based atoms generation
AdamRamberg/unity-atoms pull request #187
Opened 2020-08-07 16:36 UTC by soraphis

which scripts to generate can now be added to assets.

I've just added it ontop of the current system, so there are some redundancies.

also it has to be tested if this would regenerate assets in packages.

it also contains an custom inspector for Folders, if a folder contains "Atom" it shows a button to generate a new generation file.
not sure if we should keep this, but it could be a nice user workflow improvement. e.g. for typical used atoms (IntVariable / FloatVariable)

2020-08-10 12:35 UTC, bguyl commented
It could be nice to be able to specify an Editor folder
We use asmdef and we keep all editor related code in a single folder, currently I manually drag the generated editor files in the folder

2020-09-12 18:39 UTC, miikalo commented
Finally got around checking this out. 

Just as a test, I wanted to create a generator for https://docs.unity3d.com/ScriptReference/Rect.html but the type finder can't find it, these were the only three types found from UnityEngine:

![image](https://user-images.githubusercontent.com/1841625/93002446-71d4cf80-f537-11ea-8d7a-3546d02e44ee.png)

If I type it in manually, the generator refuses to generate since it can't find the type:

![image](https://user-images.githubusercontent.com/1841625/93002457-8749f980-f537-11ea-83de-4f7e04297eff.png)
![image](https://user-images.githubusercontent.com/1841625/93002465-94ff7f00-f537-11ea-989f-16c3138d9b48.png)

This is on a fresh project, I have restarted Unity meanwhile but the problem keeps appearing. I added the Core and BaseAtoms packages only.

Also I can't seem to find this button that should appear if a directory name has "Atom" in it, where is it located?

2020-09-14 20:29 UTC, soraphis commented
@miikalo thanks for checking it out!

I fixed the Rect issue, the button should appear when selecting a folder in the inspector.

![image](https://user-images.githubusercontent.com/3066582/93134870-aed8c780-f6d9-11ea-91e0-95e5a66caede.png)

2020-09-24 18:44 UTC, miikalo commented
Functionality-wise it's great, however I'd like all of the Atom types to generate be checked by default when creating a generator, I'd more often want to have all of them than none of them and it saves a lot of clicks. Is it also possible to have the editor jump to the newly created generator after pushing the "Add Generator" button?

I have some nits about whitespace and commented out code in the files, after those are addressed it looks good.

2020-09-24 18:45 UTC, miikalo commented on Packages/Core/Editor/Editors/AtomFolderEditor.cs
> +
Nit: extra whitespace

2020-09-24 18:45 UTC, miikalo commented on Packages/Core/Editor/Editors/AtomFolderEditor.cs
> +
Nit: extra whitespace

2020-09-24 18:45 UTC, miikalo commented on Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
> +            // EditorGUILayout.PropertyField(serializedObject.FindProperty("BaseType"));
Nit: Can be removed?

2020-09-24 18:47 UTC, miikalo requested changes

2020-09-24 18:47 UTC, miikalo commented on Packages/Core/Editor/Editors/AtomFolderEditor.cs
> +
Nit: extra whitespace

2020-09-24 18:47 UTC, miikalo commented on Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
> +            // EditorGUILayout.PropertyField(serializedObject.FindProperty("Namespace"));
Nit: commented out code can be removed in this file?

2020-09-24 18:47 UTC, miikalo commented on Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
> +
Nit: extra whitespace

2020-09-24 18:47 UTC, miikalo commented on Packages/Core/Editor/Generator/AtomGenerator.cs
> +
Nit: extra whitespace

2020-09-24 18:47 UTC, miikalo commented on Packages/Core/Editor/Generator/RegenerateAllAtoms.cs
> +            //Debug.Log(sb.ToString());
Nit: commented out code and extra whitespace can be removed?

2020-10-08 19:52 UTC, miikalo approved these changes
After a reconsideration, the changes are not absolutely necessary.

2020-11-06 21:05 UTC, miikalo approved these changes

2020-11-06 21:07 UTC, merged